### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by jehoshua02** [jehoshua02/learn-go#1]
+ [x] [Homepage](https://golang.org/doc)
+ [x] [Documentation](https://golang.org/doc/)
+ [x] [Getting Started](https://golang.org/doc/install)
+ [ ] [How to Write Go Code](https://golang.org/doc/code.html)
+ [ ] [Effective Go](https://golang.org/doc/effective_go.html)
+ [ ] [Frequently Asked Questions (FAQ)](https://golang.org/doc/faq)
+ [ ] [Command Documentation](https://golang.org/doc/cmd)
+ [ ] [Debugging Go Code with GDB](https://golang.org/doc/gdb)
+ [ ] [A Quick Guide to Go&amp;#39;s Assembler](https://golang.org/doc/asm)
+ [x] [Terms of service](https://golang.org/doc/tos.html)
+ [ ] [Contribution Guide](https://golang.org/doc/contribute.html)
+ [ ] [Go 1.8 Release Notes](https://golang.org/doc/go1.8)
+ [ ] [Go 1.7 Release Notes](https://golang.org/doc/go1.7)
+ [ ] [Go 1.6 Release Notes](https://golang.org/doc/go1.6)
+ [ ] [Go 1.5 Release Notes](https://golang.org/doc/go1.5)
+ [ ] [Go 1.4 Release Notes](https://golang.org/doc/go1.4)
+ [ ] [Go 1.3 Release Notes](https://golang.org/doc/go1.3)
+ [ ] [Go 1.2 Release Notes](https://golang.org/doc/go1.2)
+ [ ] [Go 1.1 Release Notes](https://golang.org/doc/go1.1)
+ [ ] [Contributing to the gccgo frontend](https://golang.org/doc/gccgo_contribute.html)
+ [ ] [Go 1 and the Future of Go Programs](https://golang.org/doc/go1compat)
+ [ ] [About the go command](https://golang.org/doc/articles/go_command.html)
+ [ ] [Data Race Detector](https://golang.org/doc/articles/race_detector.html)
+ [ ] [Writing Web Applications](https://golang.org/doc/articles/wiki/)
+ [ ] [doc/articles/wiki/part1.go](https://golang.org/doc/articles/wiki/part1.go)
+ [ ] [doc/articles/wiki/part2.go](https://golang.org/doc/articles/wiki/part2.go)
+ [ ] [doc/articles/wiki/part3.go](https://golang.org/doc/articles/wiki/part3.go)
+ [ ] [doc/articles/wiki/final.go](https://golang.org/doc/articles/wiki/final.go)
+ [ ] [https://golang.org/doc/codewalk/?fileprint=/doc%2Fcodewalk%2Fpig.go&amp;lo=0&amp;hi=0](https://golang.org/doc/codewalk/?fileprint=/doc%2Fcodewalk%2Fpig.go&lo=0&hi=0)
+ [ ] [https://golang.org/doc/codewalk/?fileprint=/doc%2Fcodewalk%2Fpig.go&amp;lo=17&amp;hi=21](https://golang.org/doc/codewalk/?fileprint=/doc%2Fcodewalk%2Fpig.go&lo=17&hi=21)
+ [ ] [https://golang.org/doc/codewalk/?fileprint=/doc%2Fcodewalk%2Fpig.go&amp;lo=23&amp;hi=24](https://golang.org/doc/codewalk/?fileprint=/doc%2Fcodewalk%2Fpig.go&lo=23&hi=24)
+ [ ] [https://golang.org/doc/codewalk/?fileprint=/doc%2Fcodewalk%2Fpig.go&amp;lo=26&amp;hi=41](https://golang.org/doc/codewalk/?fileprint=/doc%2Fcodewalk%2Fpig.go&lo=26&hi=41)
+ [ ] [https://golang.org/doc/codewalk/?fileprint=/doc%2Fcodewalk%2Fpig.go&amp;lo=43&amp;hi=44](https://golang.org/doc/codewalk/?fileprint=/doc%2Fcodewalk%2Fpig.go&lo=43&hi=44)
+ [ ] [https://golang.org/doc/codewalk/?fileprint=/doc%2Fcodewalk%2Fpig.go&amp;lo=48&amp;hi=53](https://golang.org/doc/codewalk/?fileprint=/doc%2Fcodewalk%2Fpig.go&lo=48&hi=53)
+ [ ] [https://golang.org/doc/codewalk/?fileprint=/doc%2Fcodewalk%2Fpig.go&amp;lo=56&amp;hi=70](https://golang.org/doc/codewalk/?fileprint=/doc%2Fcodewalk%2Fpig.go&lo=56&hi=70)
+ [ ] [https://golang.org/doc/codewalk/?fileprint=/doc%2Fcodewalk%2Fpig.go&amp;lo=72&amp;hi=89](https://golang.org/doc/codewalk/?fileprint=/doc%2Fcodewalk%2Fpig.go&lo=72&hi=89)
+ [ ] [https://golang.org/doc/codewalk/?fileprint=/doc%2Fcodewalk%2Fpig.go&amp;lo=91&amp;hi=94](https://golang.org/doc/codewalk/?fileprint=/doc%2Fcodewalk%2Fpig.go&lo=91&hi=94)
+ [ ] [https://golang.org/doc/codewalk/?fileprint=/doc%2Fcodewalk%2Fpig.go&amp;lo=110&amp;hi=121](https://golang.org/doc/codewalk/?fileprint=/doc%2Fcodewalk%2Fpig.go&lo=110&hi=121)
+ [ ] [https://golang.org/doc/codewalk/?fileprint=/doc%2Fcodewalk%2Fmarkov.go&amp;lo=6&amp;hi=44](https://golang.org/doc/codewalk/?fileprint=/doc%2Fcodewalk%2Fmarkov.go&lo=6&hi=44)
+ [ ] [https://golang.org/doc/codewalk/?fileprint=/doc%2Fcodewalk%2Fmarkov.go&amp;lo=77&amp;hi=77](https://golang.org/doc/codewalk/?fileprint=/doc%2Fcodewalk%2Fmarkov.go&lo=77&hi=77)
+ [ ] [https://golang.org/doc/codewalk/?fileprint=/doc%2Fcodewalk%2Fmarkov.go&amp;lo=76&amp;hi=79](https://golang.org/doc/codewalk/?fileprint=/doc%2Fcodewalk%2Fmarkov.go&lo=76&hi=79)
+ [ ] [https://golang.org/doc/codewalk/?fileprint=/doc%2Fcodewalk%2Fmarkov.go&amp;lo=82&amp;hi=84](https://golang.org/doc/codewalk/?fileprint=/doc%2Fcodewalk%2Fmarkov.go&lo=82&hi=84)
+ [ ] [https://golang.org/doc/codewalk/?fileprint=/doc%2Fcodewalk%2Fmarkov.go&amp;lo=60&amp;hi=60](https://golang.org/doc/codewalk/?fileprint=/doc%2Fcodewalk%2Fmarkov.go&lo=60&hi=60)
+ [ ] [https://golang.org/doc/codewalk/?fileprint=/doc%2Fcodewalk%2Fmarkov.go&amp;lo=63&amp;hi=65](https://golang.org/doc/codewalk/?fileprint=/doc%2Fcodewalk%2Fmarkov.go&lo=63&hi=65)
+ [ ] [https://golang.org/doc/codewalk/?fileprint=/doc%2Fcodewalk%2Fmarkov.go&amp;lo=88&amp;hi=100](https://golang.org/doc/codewalk/?fileprint=/doc%2Fcodewalk%2Fmarkov.go&lo=88&hi=100)
+ [ ] [https://golang.org/doc/codewalk/?fileprint=/doc%2Fcodewalk%2Fmarkov.go&amp;lo=89&amp;hi=89](https://golang.org/doc/codewalk/?fileprint=/doc%2Fcodewalk%2Fmarkov.go&lo=89&hi=89)
+ [ ] [https://golang.org/doc/codewalk/?fileprint=/doc%2Fcodewalk%2Fmarkov.go&amp;lo=90&amp;hi=90](https://golang.org/doc/codewalk/?fileprint=/doc%2Fcodewalk%2Fmarkov.go&lo=90&hi=90)
+ [ ] [https://golang.org/doc/codewalk/?fileprint=/doc%2Fcodewalk%2Fmarkov.go&amp;lo=92&amp;hi=95](https://golang.org/doc/codewalk/?fileprint=/doc%2Fcodewalk%2Fmarkov.go&lo=92&hi=95)
+ [ ] [https://golang.org/doc/codewalk/?fileprint=/doc%2Fcodewalk%2Fmarkov.go&amp;lo=96&amp;hi=97](https://golang.org/doc/codewalk/?fileprint=/doc%2Fcodewalk%2Fmarkov.go&lo=96&hi=97)
+ [ ] [https://golang.org/doc/codewalk/?fileprint=/doc%2Fcodewalk%2Fmarkov.go&amp;lo=98&amp;hi=98](https://golang.org/doc/codewalk/?fileprint=/doc%2Fcodewalk%2Fmarkov.go&lo=98&hi=98)
+ [ ] [https://golang.org/doc/codewalk/?fileprint=/doc%2Fcodewalk%2Fmarkov.go&amp;lo=68&amp;hi=71](https://golang.org/doc/codewalk/?fileprint=/doc%2Fcodewalk%2Fmarkov.go&lo=68&hi=71)
+ [ ] [https://golang.org/doc/codewalk/?fileprint=/doc%2Fcodewalk%2Fmarkov.go&amp;lo=103&amp;hi=116](https://golang.org/doc/codewalk/?fileprint=/doc%2Fcodewalk%2Fmarkov.go&lo=103&hi=116)
+ [ ] [https://golang.org/doc/codewalk/?fileprint=/doc%2Fcodewalk%2Fmarkov.go&amp;lo=107&amp;hi=110](https://golang.org/doc/codewalk/?fileprint=/doc%2Fcodewalk%2Fmarkov.go&lo=107&hi=110)
+ [ ] [https://golang.org/doc/codewalk/?fileprint=/doc%2Fcodewalk%2Fmarkov.go&amp;lo=111&amp;hi=113](https://golang.org/doc/codewalk/?fileprint=/doc%2Fcodewalk%2Fmarkov.go&lo=111&hi=113)
+ [ ] [https://golang.org/doc/codewalk/?fileprint=/doc%2Fcodewalk%2Fmarkov.go&amp;lo=115&amp;hi=115](https://golang.org/doc/codewalk/?fileprint=/doc%2Fcodewalk%2Fmarkov.go&lo=115&hi=115)
+ [ ] [https://golang.org/doc/codewalk/?fileprint=/doc%2Fcodewalk%2Fmarkov.go&amp;lo=119&amp;hi=121](https://golang.org/doc/codewalk/?fileprint=/doc%2Fcodewalk%2Fmarkov.go&lo=119&hi=121)
+ [ ] [https://golang.org/doc/codewalk/?fileprint=/doc%2Fcodewalk%2Fmarkov.go&amp;lo=123&amp;hi=124](https://golang.org/doc/codewalk/?fileprint=/doc%2Fcodewalk%2Fmarkov.go&lo=123&hi=124)
+ [ ] [https://golang.org/doc/codewalk/?fileprint=/doc%2Fcodewalk%2Fmarkov.go&amp;lo=126&amp;hi=127](https://golang.org/doc/codewalk/?fileprint=/doc%2Fcodewalk%2Fmarkov.go&lo=126&hi=127)
+ [ ] [https://golang.org/doc/codewalk/?fileprint=/doc%2Fcodewalk%2Fmarkov.go&amp;lo=128&amp;hi=129](https://golang.org/doc/codewalk/?fileprint=/doc%2Fcodewalk%2Fmarkov.go&lo=128&hi=129)
+ [ ] [https://golang.org/doc/codewalk/?fileprint=/doc%2Fcodewalk%2Fmarkov.go&amp;lo=0&amp;hi=0](https://golang.org/doc/codewalk/?fileprint=/doc%2Fcodewalk%2Fmarkov.go&lo=0&hi=0)
+ [ ] [https://golang.org/doc/codewalk/?fileprint=/doc%2Fcodewalk%2Furlpoll.go&amp;lo=0&amp;hi=0](https://golang.org/doc/codewalk/?fileprint=/doc%2Fcodewalk%2Furlpoll.go&lo=0&hi=0)
+ [ ] [https://golang.org/doc/codewalk/?fileprint=/doc%2Fcodewalk%2Furlpoll.go&amp;lo=26&amp;hi=30](https://golang.org/doc/codewalk/?fileprint=/doc%2Fcodewalk%2Furlpoll.go&lo=26&hi=30)
+ [ ] [https://golang.org/doc/codewalk/?fileprint=/doc%2Fcodewalk%2Furlpoll.go&amp;lo=60&amp;hi=64](https://golang.org/doc/codewalk/?fileprint=/doc%2Fcodewalk%2Furlpoll.go&lo=60&hi=64)
+ [ ] [https://golang.org/doc/codewalk/?fileprint=/doc%2Fcodewalk%2Furlpoll.go&amp;lo=86&amp;hi=92](https://golang.org/doc/codewalk/?fileprint=/doc%2Fcodewalk%2Furlpoll.go&lo=86&hi=92)
+ [ ] [https://golang.org/doc/codewalk/?fileprint=/doc%2Fcodewalk%2Furlpoll.go&amp;lo=66&amp;hi=77](https://golang.org/doc/codewalk/?fileprint=/doc%2Fcodewalk%2Furlpoll.go&lo=66&hi=77)
+ [ ] [https://golang.org/doc/codewalk/?fileprint=/doc%2Fcodewalk%2Furlpoll.go&amp;lo=94&amp;hi=116](https://golang.org/doc/codewalk/?fileprint=/doc%2Fcodewalk%2Furlpoll.go&lo=94&hi=116)
+ [ ] [https://golang.org/doc/codewalk/?fileprint=/doc%2Fcodewalk%2Furlpoll.go&amp;lo=95&amp;hi=96](https://golang.org/doc/codewalk/?fileprint=/doc%2Fcodewalk%2Furlpoll.go&lo=95&hi=96)
+ [ ] [https://golang.org/doc/codewalk/?fileprint=/doc%2Fcodewalk%2Furlpoll.go&amp;lo=98&amp;hi=99](https://golang.org/doc/codewalk/?fileprint=/doc%2Fcodewalk%2Furlpoll.go&lo=98&hi=99)
+ [ ] [https://golang.org/doc/codewalk/?fileprint=/doc%2Fcodewalk%2Furlpoll.go&amp;lo=101&amp;hi=104](https://golang.org/doc/codewalk/?fileprint=/doc%2Fcodewalk%2Furlpoll.go&lo=101&hi=104)
+ [ ] [https://golang.org/doc/codewalk/?fileprint=/doc%2Fcodewalk%2Furlpoll.go&amp;lo=106&amp;hi=111](https://golang.org/doc/codewalk/?fileprint=/doc%2Fcodewalk%2Furlpoll.go&lo=106&hi=111)
+ [ ] [https://golang.org/doc/codewalk/?fileprint=/doc%2Fcodewalk%2Furlpoll.go&amp;lo=113&amp;hi=115](https://golang.org/doc/codewalk/?fileprint=/doc%2Fcodewalk%2Furlpoll.go&lo=113&hi=115)
+ [ ] [https://golang.org/doc/codewalk/?fileprint=/doc%2Fcodewalk%2Furlpoll.go&amp;lo=79&amp;hi=84](https://golang.org/doc/codewalk/?fileprint=/doc%2Fcodewalk%2Furlpoll.go&lo=79&hi=84)
+ [ ] [https://golang.org/doc/codewalk/?fileprint=/doc%2Fcodewalk%2Furlpoll.go&amp;lo=32&amp;hi=50](https://golang.org/doc/codewalk/?fileprint=/doc%2Fcodewalk%2Furlpoll.go&lo=32&hi=50)
+ [ ] [https://golang.org/doc/codewalk/?fileprint=/doc%2Fcodewalk%2Furlpoll.go&amp;lo=36&amp;hi=36](https://golang.org/doc/codewalk/?fileprint=/doc%2Fcodewalk%2Furlpoll.go&lo=36&hi=36)
+ [ ] [https://golang.org/doc/codewalk/?fileprint=/doc%2Fcodewalk%2Furlpoll.go&amp;lo=37&amp;hi=37](https://golang.org/doc/codewalk/?fileprint=/doc%2Fcodewalk%2Furlpoll.go&lo=37&hi=37)
+ [ ] [https://golang.org/doc/codewalk/?fileprint=/doc%2Fcodewalk%2Furlpoll.go&amp;lo=38&amp;hi=38](https://golang.org/doc/codewalk/?fileprint=/doc%2Fcodewalk%2Furlpoll.go&lo=38&hi=38)
+ [ ] [https://golang.org/doc/codewalk/?fileprint=/doc%2Fcodewalk%2Furlpoll.go&amp;lo=39&amp;hi=48](https://golang.org/doc/codewalk/?fileprint=/doc%2Fcodewalk%2Furlpoll.go&lo=39&hi=48)
+ [ ] [First-Class Functions in Go](https://golang.org/doc/codewalk/functions/)
+ [ ] [Generating arbitrary text: a Markov chain algorithm](https://golang.org/doc/codewalk/markov/)
+ [ ] [Share Memory By Communicating](https://golang.org/doc/codewalk/sharemem/)
+ [ ] [Release History](https://golang.org/doc/devel/release.html)
+ [ ] [Weekly Snapshot History](https://golang.org/doc/devel/weekly.html)
+ [ ] [Pre-Go 1 Release History](https://golang.org/doc/devel/pre_go1.html)
+ [ ] [Installing Go from source](https://golang.org/doc/install/source)
+ [ ] [Setting up and using gccgo](https://golang.org/doc/install/gccgo)
